version: '3.8'
services:

  app:
    
    build: .
    container_name: LeChene_User_service
    volumes:
      - .:/app

    ports:
      - "5001:5001"
  
    links:
      - api_mongo
   

  api_mongo:
    image: mongo:4.0.28-xenial
    container_name: LeChene_User_service_db
    volumes:
      - mongodb_api:/data/db
     
    ports:
      - "27017:27017"
    
    environment:
      - MONGO_INITDB_DATABASE=user_service_db

volumes:
  mongodb_api:

  
